kafka:
  bootstrap.servers: "localhost:9092"

  click:
    topic:   "click-topic"
    group.id: "click-group"

  model:
    topic:    "model-topic"
    group.id: "model-group"

  pricing:
    topic:                 "pricing-results"
    transactional.id.prefix: "pricing-txn-"

  alerts:
    topic:                 "pricing-alerts"
    transactional.id.prefix: "pricing-alerts-txn-"

inventoryCdc:
  host:     "db-host"
  port:     3306
  database: "warehouse_db"
  table:    "inventory"
  user:     "dbuser"
  password: "dbpass"

priceRuleCdc:
  host:     "db-host"
  port:     3306
  database: "pricing_db"
  table:    "price_rules"
  user:     "dbuser"
  password: "dbpass"

orderCdc:
  host:     "db-host"
  port:     3306
  database: "shop_db"
  table:    "orders"
  user:     "dbuser"
  password: "dbpass"

competitor:
  api:
    base-url: "http://api.example.com"