kafka:
  bootstrap.servers: "localhost:9092"

  click:
    topic: "clicks"
    group-id: "click-group"

  model:
    topic: "ml-model"
    group-id: "model-group"

  pricing:
    topic: "pricing-results"
    transactional.id.prefix: "pricing-txn-"

  alerts:
    topic:  "pricing-alerts"
    transactional.id.prefix: "pricing-alerts-txn-"

  inventory:
    topic: "inventory-level"
    group-id: "inventory--group"

  priceRule:
    topic: "price-rules"
    group-id: "price-rules-group"

  orders:
    topic: "orders"
    group-id: "orders-group"

competitor:
  api:
    base-url: "http://api.example.com"